### ISSUE TITLE
Not working in combination with "logged in as guest"

### ISSUE THREAD

**Issue by create-martin** [catalyst/moodle-local_login#10]
Me again - sorry :-/

I just came across another interesting behaviour. The page I tested splash with uses the guest accounts. 
When logged in as a guest, an then clicking on the Login-Link in the top right corner, nothing happens (to be more precise: the current page gets reloaded:

![image](https://user-images.githubusercontent.com/1061340/193998553-58826c6d-f09f-4860-8e08-f1a983439b2c.png)

**Comment by danmarsden** [comment]
no apologies needed - nice catch - I think we need a check against the guest login here:
https://github.com/catalyst/moodle-local_login/blob/main/index.php#L31

**Comment by danmarsden** [comment]
I've just pushed a fix into the repository that should fix that - thanks!

**Comment by create-martin** [comment]
Sure. Just a thought: would it make sense, to make „Login as a guest“ one of the options of the splash page (if enabled)? My knowledge on authentication is somewhat limited, so I’m not sure, if that would make any sense from an architectural point of view…

Thanks for the fix!

***@***.***
Wir leben Lernen.
***@***.***<https://www.facebook.com/CREATE.Digital.Learning>  ***@***.*** <https://www.linkedin.com/company/758246?trk=tyah&trkInfo=idx%3A1-1-1%2CtarId%3A1425468563071%2Ctas%3Acreate+mediadesign>   ***@***.*** <https://www.create.at/>   ***@***.*** <http://www.cbook.de/>
create-mediadesign GmbH
ATU 50420904 | HG Wien-FN 201256s
Wien: A-1040 | Taubstummengasse 7/3
München: 81375 | Würmtalstraße 20 A
DI(FH) Martin Berger
Senior Technical Consultant
***@***.***    ***@***.******@***.***>
***@***.***    +43 1 78 66 318 22<tel:+431786631822>
***@***.***    create.at<https://create.at/> | cBook.de<http://www.cbook.de>

For a better 21st century.

Von: Dan Marsden ***@***.***>
Gesendet: Donnerstag, 6. Oktober 2022 03:07
An: catalyst/moodle-local_login ***@***.***>
Cc: Martin Berger ***@***.***>; Author ***@***.***>
Betreff: Re: [catalyst/moodle-local_login] Not working in combination with "logged in as guest" (Issue #10)


no apologies needed - nice catch - I think we need a check against the guest login here:

**Comment by danmarsden** [comment]
interesting idea - I've just created #11 to consider that in future.
