### ISSUE TITLE
Bypass alternateloginurl

### ISSUE THREAD

**Issue by SashaAnastasi** [catalyst/moodle-local_login#17]
In Tōtara 15 and onwards `alternateloginurl` is deprecated and disabled unless the config setting `allowlogincsrf` is enabled.
Enabling this setting carries security implications.

Since `alternateloginurl` is only being used as a shortcut to the login page for this plugin and the login page's URL won't vary when this plugin is being used, a solution could be to hardcode the relative login URL in the plugin rather than using `alternateloginurl`.

**Comment by danmarsden** [comment]
duplicate of #14 which is fixed and rolling out into catalyst locals today
