### ISSUE TITLE
Background Image displayed in Footer

### ISSUE THREAD

**Issue by create-martin** [catalyst/moodle-local_login#9]
Hi, I just tested the Plugin and like it a lot!
Everything works as expected, however, if I add a background-image, it's displayed only in the Footer-Area:

![image](https://user-images.githubusercontent.com/1061340/193792904-c0363dbd-4816-4a76-9954-e5a5997e056c.png)

Note: I'm using Moodle 4.0.2 and "Union" as a Theme and I activated the "Impressum", thus creating the Footer-Area. However. Disabling the Impressum doesn't help, then the image is not shown at all.

All the best,
Martin

**Comment by danmarsden** [comment]
I'm inclined to ask you to report this to the union theme developer - all we do to add the background to the page is add this simple css here:
https://github.com/catalyst/moodle-local_login/blob/main/styles.css#L23-L25

something in the union theme is obviously overriding that and dropping the grey background in place.

Of course - feel free to re-open if the union theme developer suggests something that is generic (and not speific to union) that we can add to our plugin to make it support a wider range of themes, but I'm closing this for now.

thanks!

**Comment by mickaelclavreul** [comment]
Hi,

Something similar occurs to me. 
When I select an image to display as background, I only get a gray-filled background and can't see my image.
I'm using Moodle 4.5.5 with Boost theme.

To make it work, I need to add a new rule to styles.css such as:
`#page-local-login-index #page {
    background-image: url([[pix:local_login|backgroundimage]]); // Same as the original rule
    background-size: cover;      /* Makes the image cover the whole div */
    background-repeat: no-repeat; /* Prevents tiling */
    background-position: center;  /* Centers the image */
}`

Is it good practice or did I miss something?

Regards.

**Comment by danmarsden** [comment]
thanks @mickaelclavreul - the code was initially wrote for an older moodle release, so it's highly possible that we should be updating the CSS in this plugin to target #page as well - feel free to submit a PR for us to take a look (but otherwise your css looks like it does what you needed.) :-)
